# Settings
permalink: pretty

url: "theinfinityglitch.github.io"

collections_dir: collections
collections:
  article:
    output: true
  devlog:
    output: true

# Build collection items with a future date.
future: true

# Plugins
plugins:
  - jekyll-paginate-v2
  - jekyll-redirect-from

# Internationalization
lang: "en"

# Pagination (used by the blog)
pagination:
  enabled: true
  debug: false

  collection: "article"
  per_page: 24
  sort_field: "date"
  sort_reverse: true
  # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2

  title: ":title - Page :num"
  permalink: "/:num/"
  category: "posts"
  tag: ""
  locale: ""

title: The Infinity Glitch

# .scss generation
sass:
  sass_dir: _sass
  style: compressed
